<?php

namespace PostBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get post by $id
     *
     * @param int $id
     * @return mixed
     */
    public function getPostById(int $id)
    {
        return $this->_em
            ->createQuery('SELECT p
                           FROM PostBundle:Post p
                           WHERE p.id = :id')
            ->setParameter('id', $id)
            ->getSingleResult();
    }

    /**
     * Get all posts
     *
     * @return array
     */
    public function getAllPost()
    {
        return $this->_em
            ->createQuery('SELECT p FROM PostBundle:Post p')
            ->getResult();
    }
}
